package com.mbrdi.anita.message.model;

public enum ACTION {
    UPDATE_PROFILE, UPDATE_GUARDIANS, SYNC_TRACKS, READ_MESSAGE, UPDATE_APP, PRE_START_JOURNEY, START_JOURNEY,
    END_JOURNEY, GET_NOTIFICATION, UPDATE_CONFIG, REQ_SEND_LOCATION, ADMIN_NOTIFICATION, DELETE_MESSAGE_GROUP,
    PRE_JOURNEY_NOTIFY, SYNC_TRIP_HISTORY, UPDATE_TRIP, RUN_DAILY_UPDATE, UPDATE_LOCATION,
    TRAVEL_GRP_JOIN_REQ, TRAVEL_REQ_UPDATE, TRAVEL_GRP_JOIN_REQ_ACCEPT, TRAVEL_GRP_SYNC, TRAVEL_GRP_JOURNEY_START,
    TRAVEL_GRP_JOURNEY_STOP, UPDATE_TRIP_EVENT, TRAVEL_REQ_SYNC, TRAVEL_GRP_DELETED;
}
